version: '3.8'
services:
  backend:
    image: fsbt-back
    container_name: fsbt-back
    build: ./back-end
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./back-end/test.db:/usr/src/app/back-end/test.db
      - ./back-end/main.py:/usr/src/app/back-end/main.py

  db:
    image: postgres:latest
    container_name: fsbt-db
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: