version: '3.8'

services:
  backend:
    image: fsbt-back
    container_name: fsbt-back
    build: ./back-end
    ports:
      - "8000:8000"
    volumes:
      - ./back-end/test.db:/usr/src/app/back-end/test.db
   
  # simulator:
  #   image: fsbt-sim
  #   container_name: fsbt-sim
  #   build: ./simulator
  #   environment:
  #     SOCKETIO_IP: 34.141.148.0
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - backend

  frontend:
    image: fsbt-front
    container_name: fsbt-front
    build: ./front-end
    ports:
      - "80:80"
    depends_on:
      - simulator
