version: '3.8'

services:
  backend:
    image: fsbt-back
    container_name: fsbt-back
    build: ./back-end
    ports:
      - "8000:8000"
    volumes:
      - ./back-end/test.db:/usr/src/app/back-end/test.db

  frontend:
    image: fsbt-front
    container_name: fsbt-front
    build: ./front-end
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./front-end/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/fossbot-platform.duckdns.org/fullchain.pem:/etc/letsencrypt/live/fossbot-platform.duckdns.org/fullchain.pem
      - /etc/letsencrypt/live/fossbot-platform.duckdns.org/privkey.pem:/etc/letsencrypt/live/fossbot-platform.duckdns.org/privkey.pem
    depends_on:
      - backend
